=== canyudeguang/Zigbee_lamp/target/sectools/qdn/config/xsd/iot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.qualcomm.com/iot"
    xmlns:tns="http://www.qualcomm.com/iot">

    <element name="iot">
        <complexType>
            <all>
                <element name="metadata" type="tns:complex_metadata"/>
                <element name="general_properties" type="tns:complex_general_properties"/>
                <element name="parsegen" type="tns:complex_parsegen"/>
                <element name="images_list" type="tns:complex_images_list" />
                <element name="data_provisioning" type="tns:complex_data_provisioning"/>
            </all>
        </complexType>
    </element>

    <complexType name="complex_metadata">
        <all>
            <element name="chipset" type="string" maxOccurs="1" minOccurs="0" default="default"/>
            <element name="version" type="string" maxOccurs="1" minOccurs="0" default="1.0"/>
        </all>
    </complexType>

    <complexType name="complex_general_properties">
        <all>
            <element name="selected_cert_config" type="string" maxOccurs="1" minOccurs="0" default="iot"/>
            <element name="selected_signer" type="string" maxOccurs="1" minOccurs="0" default="base"/>
            <element name="max_cert_size" type="int" maxOccurs="1" minOccurs="0" default="2048"/>
            <element name="key_size" type="int" maxOccurs="1" minOccurs="0" default="2048"/>
            <element name="exponent" type="int" maxOccurs="1" minOccurs="0" default="257"/>
            <element name="num_certs_in_certchain" type="int" maxOccurs="1" minOccurs="0" default="2"/>
            <element name="num_root_certs" type="int" maxOccurs="1" minOccurs="0" default="1"/>
            <element name="max_num_root_certs" type="int" maxOccurs="1" minOccurs="0" default="1"/>
            <element name="msm_part" type="string" maxOccurs="1" minOccurs="0" default="0x00000000"/>
            <element name="sw_id" type="string" maxOccurs="1" minOccurs="0" default="0x0000000000000000"/>
            <element name="oem_id" type="string" maxOccurs="1" minOccurs="0" default="0x0000"/>
            <element name="model_id" type="string" maxOccurs="1" minOccurs="0" default="0x0000"/>
            <element name="soc_hw_version" type="string" maxOccurs="1" minOccurs="0" default="0x00000000"/>
            <element name="in_use_soc_hw_version" type="int" maxOccurs="1" minOccurs="0" default="0"/>
            <element name="use_serial_number_in_signing" type="int" maxOccurs="1" minOccurs="0" default="0"/>
            <element name="debug" type="string" maxOccurs="1" minOccurs="0" default="0x0000000000000000"/>
            <element name="hash_algorithm" type="string" maxOccurs="1" minOccurs="0" default="sha256"/>
            <element name="segment_hash_algorithm" type="string" maxOccurs="1" minOccurs="0" default="sha256"/>
            <element name="rsa_padding" type="string" maxOccurs="1" minOccurs="0" default="pkcs"/>
            <element name="hmac" type="boolean" maxOccurs="1" minOccurs="0" default="true"/>
            <element name="secboot_version" type="string" maxOccurs="1" minOccurs="0" default="1.0"/>
            <element name="oem_sign" type="boolean" maxOccurs="1" minOccurs="0" default="true"/>
            <element name="dsa_type" type="string" maxOccurs="1" minOccurs="0" default="rsa"/>
        </all>
    </complexType>

    <complexType name="complex_parsegen">
        <all>
            <element name="image_types_list" type="tns:complex_image_types_list" maxOccurs="1" minOccurs="0"/>
        </all>
    </complexType>

    <complexType name="complex_image_types_list">
        <sequence>
            <element name="image_type" type="tns:complex_image_type" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="complex_image_type">
        <all>
            <element name="file_type" type="string" maxOccurs="1" minOccurs="0" default="elf"/>
            <element name="mbn_properties" type="tns:complex_mbn_properties" maxOccurs="1" minOccurs="0" />
            <element name="elf_properties" type="tns:complex_elf_properties" maxOccurs="1" minOccurs="0"/>
        </all>
        <attribute name="id" type="string" use="required"/>
    </complexType>

    <complexType name="complex_mbn_properties">
        <all>
            <element name="header_size" type="int" />
        </all>
    </complexType>

    <complexType name="complex_elf_properties">
        <all>
            <element name="max_elf_segments" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="hash_seg_placement" type="string" maxOccurs="1" minOccurs="0"/>
            <element name="image_type" type="int" maxOccurs="1" minOccurs="0" default="0"/>
            <element name="has_hash_table" type="boolean" maxOccurs="1" minOccurs="0" default="true"/>
            <element name="validate_ph_addrs" type="boolean" maxOccurs="1" minOccurs="0" default="true"/>
            <element name="validate_vir_addrs" type="boolean" maxOccurs="1" minOccurs="0" default="false"/>
        </all>
    </complexType>

    <complexType name="complex_data_provisioning">
        <all>
            <element name="base_path" type="string" maxOccurs="1" minOccurs="0"
                     default="./../../resources/data_prov_assets/"/>
        </all>
    </complexType>

    <complexType name="complex_images_list">
        <sequence>
            <element name="image" type="tns:complex_image" maxOccurs="unbounded" minOccurs="1" />
        </sequence>
    </complexType>

    <complexType name="complex_image">
        <all>
            <element name="general_properties_overrides" type="tns:complex_general_properties_overrides" />
        </all>
        <attribute name="sign_id" type="string" use="required" />
        <attribute name="image_type" type="string" use="required" />
        <attribute name="name" type="string" use="optional" />
        <attribute name="cert_config" type="string" use="optional" />
        <attribute name="output_file_name" type="string" use="optional" />
    </complexType>

    <complexType name="complex_general_properties_overrides">
        <all>
            <element name="selected_cert_config" type="string" maxOccurs="1" minOccurs="0" />
            <element name="selected_signer" type="string" maxOccurs="1" minOccurs="0" />
            <element name="max_cert_size" type="int" maxOccurs="1" minOccurs="0" />
            <element name="key_size" type="int" maxOccurs="1" minOccurs="0" />
            <element name="exponent" type="int" maxOccurs="1" minOccurs="0" />
            <element name="num_certs_in_certchain" type="int" maxOccurs="1" minOccurs="0" />
            <element name="num_root_certs" type="int" maxOccurs="1" minOccurs="0" />
            <element name="max_num_root_certs" type="int" maxOccurs="1" minOccurs="0" />
            <element name="msm_part" type="string" maxOccurs="1" minOccurs="0" />
            <element name="sw_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="oem_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="model_id" type="string" maxOccurs="1" minOccurs="0" />
            <element name="soc_hw_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="in_use_soc_hw_version" type="int" maxOccurs="1" minOccurs="0" />
            <element name="use_serial_number_in_signing" type="int" maxOccurs="1" minOccurs="0" />
            <element name="debug" type="string" maxOccurs="1" minOccurs="0" />
            <element name="hash_algorithm" type="string" maxOccurs="1" minOccurs="0" />
            <element name="segment_hash_algorithm" type="string" maxOccurs="1" minOccurs="0" />
            <element name="rsa_padding" type="string" maxOccurs="1" minOccurs="0" />
            <element name="hmac" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="secboot_version" type="string" maxOccurs="1" minOccurs="0" />
            <element name="oem_sign" type="boolean" maxOccurs="1" minOccurs="0" />
            <element name="dsa_type" type="string" maxOccurs="1" minOccurs="0" />
        </all>
    </complexType>

</schema>

=== canyudeguang/Zigbee_lamp/target/sectools/qdn/config/4020/4020_iot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================
Copyright (c) 2013-2018 Qualcomm Technologies, Inc.
All Rights Reserved.
===============================================================================
-->
<!--
Copyright (c) 2018 Qualcomm Technologies, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below)
provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Qualcomm Technologies, Inc. nor the names of its contributors may be used to endorse or promote products derived
from this software without specific prior written permission.
NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->

<tns:iot xmlns:tns="http://www.qualcomm.com/iot"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.qualcomm.com/iot ../xsd/iot.xsd">

    <!-- This is for QCA4020 target -->
    <metadata>
        <chipset>4020</chipset>
    </metadata>

    <general_properties>
        <msm_part>0x000160E1</msm_part>
        <in_use_soc_hw_version>1</in_use_soc_hw_version>
        <soc_hw_version>0x40030000</soc_hw_version>
        <debug>0x0000000000000002</debug>
    </general_properties>

    <parsegen>
        <image_types_list>
            <image_type id='elf_has_ht'>
                <elf_properties></elf_properties>
            </image_type>
        </image_types_list>
    </parsegen>

    <data_provisioning></data_provisioning>

    <images_list>
        <image sign_id="m4" name="m4.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000000</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="kf" name="kf.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000001</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="m0" name="m0.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000002</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="m4_golden" name="m4_golden.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000003</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="kf_golden" name="kf_golden.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000004</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="m0_golden" name="m0_golden.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000005</sw_id>
            </general_properties_overrides>
        </image>

        <image sign_id="otp_patch_update" name="otp_patch_update.mbn" image_type="elf_has_ht">
            <general_properties_overrides>
                <sw_id>0x0000000000000006</sw_id>
            </general_properties_overrides>
        </image>
    </images_list>

</tns:iot>
